name: coupon_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  color: ^2.1.1
  sprintf: ^4.0.2
  carousel_slider: ^1.4.1
  font_awesome_flutter: ^8.8.1
  flutter_html: ^0.11.1
  flutter_staggered_grid_view: ^0.3.0
  timetable: ^0.2.6
  table_calendar: ^2.2.3
  provider: ^3.2.0
  oktoast: ^2.3.2
  http: ^0.12.0+4
  get_it: ^1.0.3
  shared_preferences: ^0.5.6+3
  flutter_spinkit: ^4.1.2
  pull_to_refresh: ^1.6.0
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
  path_provider: ^1.6.11
  smooth_star_rating: ^1.1.1
  geolocator: ^5.3.2+2
  email_validator: ^1.0.0
  url_launcher: ^5.5.0
  fluttertoast: ^7.1.1
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  numberpicker: ^1.3.0
  qr_flutter: ^3.2.0
  share: ^0.6.5+4
  screenshot: ^0.2.0
  qr_code_scanner: ^0.3.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/loca_home.png
    - assets/drop_pin.png
    - assets/background_sign_in_image.jpg
    - assets/f_13.png
    - assets/f_18.png
    - assets/f_19.png
    - assets/f_20.png
    - assets/f_21.png
    - assets/f_22.png
    - assets/f_23.png
    - assets/f_26.png
    - assets/f_27.png
    - assets/f_28.png
    - assets/f_29.png
    - assets/f_30.png
    - assets/f_31.png
    - assets/f_32.png
    - assets/f_33.png
    - assets/f_34.png
    - assets/f_35.png
    - assets/f_39.png
    - assets/f_41.png
    - assets/f_55.png
    - assets/f_74.png
    - assets/f_76.png
    - assets/f_92.png
    - assets/f_93.png
    - assets/f_107.png
    - assets/f_108.png
    - assets/f_110.png
    - assets/f_111.png
    - assets/f_131.png
    - assets/f_132.png
    - assets/f_133.png
    - assets/f_138.png
    - assets/f_160.png
    - assets/f_161.png
    - assets/f_162.png
    - assets/f_163.png
    - assets/f_164.png
    - assets/f_165.png
    - assets/f_166.png
    - assets/f_167.png
    - assets/f_169.png
    - assets/f_170.png
    - assets/f_171.png
    - assets/f_177.png
    - assets/razorpay.png
    - assets/cod.png
    - assets/illustration.png
    - assets/illustration2.png
    - assets/illustration3.png
    - assets/illustration3.jpg
    - assets/illustration4.jpg
    - assets/ic_launcher.jpeg
    - assets/user_information_background.jpg
    - assets/login_screen_image.jpg
    - assets/login_icon.jpeg
    - assets/icons/1.jpg
    - assets/icons/2.png
    - assets/mi_logo.jpeg
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin