version: "3.7"

services:
  app:
    container_name: food-coupon-app
    build:
      context: .
    volumes:
      - ./coupon-app:/coupon-app
      - static_data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=couponapp
      - DB_USER=postgres
      - DB_PASS=aditi123
      - DEBUG=0
      - ALLOWED_HOSTS=35.226.77.40
    depends_on:
      - db
      - cache
  proxy:
    container_name: nginx-proxy
    image: proxy:latest
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - static_data:/vol/static

  db:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - pgsql_data:/var/lib/pgsql/data/
    environment:
      - POSTGRES_DB=couponapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aditi123

  cache:
    container_name: cache
    image: memcached
    ports:
      - "11212:11211"
    entrypoint:
      - memcached
      - -m 64
  web:
    container_name: web
    build:
      context: ./web/coupon-app
    depends_on:
        - proxy
    ports:
      - "8080:80"

    volumes:
      - ./web/coupon-app:/web/coupon-app
  #      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #      - ./web/coupon-app:/coupon-app:cached
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  static_data:
  pgsql_data:
