# Generated by Django 2.2.16 on 2021-02-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210204_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='fk_vendor_redeemed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vendor'),
        ),
    ]
